version: '3'
volumes:
  gerrit-site-volume:
  gerrit-repositories-volume:
  postgres-volume:
services:
  gerrit:
    build: .
    container_name: gerrit
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gerrit-site-volume:/var/gerrit/review_site
      - gerrit-repositories-volume:/var/git
    ports:
      - 8080:8080
      - 29418:29418
    environment:
      GERRIT_INIT_ARGS: --install-plugin=download-commands --install-plugin=singleusergroup --install-plugin=commit-message-length-validator
      WEBURL: http://localhost:8080
      USER_NAME: gerrit
      USER_EMAIL: gerrit@lse.epita.fr
      GITWEB_TYPE: gitiles
      DATABASE_TYPE: postgresql
      DB_PORT_5432_TCP_ADDR: postgres-gerrit
      DB_PORT_5432_TCP_PORT: 5432
      DB_ENV_POSTGRES_USER: postgres
      DB_ENV_POSTGRES_PASSWORD: qw2fG2dfl0mxW
      DB_ENV_POSTGRES_DB: reviewdb
      AUTH_TYPE: LDAP
      LDAP_SERVER: ldaps://auth.pie.cri.epita.net
      LDAP_ACCOUNTBASE: ou=users,dc=epita,dc=net
      LDAP_ACCOUNTPATTERN: (&(|(memberOf=cn=2019_gistre,ou=classGroups,dc=epita,dc=net)(uid=alizee.penel))(uid=$${username}))
      LDAP_SSLVERIFY: "false"
      SMTP_SERVER: mail.cri.epita.net
      SMTP_SERVER_PORT: 587
      SMTP_CONNECT_TIMEOUT: 10sec
      SMTP_FROM: USER
    links:
      - postgres-gerrit
    depends_on:
      - postgres-gerrit
  postgres-gerrit:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: qw2fG2dfl0mxW
      POSTGRES_DB: reviewdb
