version: '3'
volumes:
  gerrit-site-volume:
  gerrit-repositories-volume:
  postgres-volume:
services:
  gerrit:
    build: .
    container_name: gerrit
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gerrit-site-volume:/var/gerrit/review_site
      - gerrit-repositories-volume:/var/git
    ports:
      - 8080:8080
      - 29418:29418
    environment:
      GERRIT_INIT_ARGS: --install-plugin=download-commands --install-plugin=singleusergroup
      WEBURL: http://localhost:8080
      USER_NAME: gerrit
      USER_EMAIL: gerrit@lse.epita.fr
      GITWEB_TYPE: gitiles
      DATABASE_TYPE: postgresql
      DB_PORT_5432_TCP_ADDR: 172.16.238.10
      DB_PORT_5432_TCP_PORT: 5432
      DB_ENV_POSTGRES_USER: postgres
      DB_ENV_POSTGRES_PASSWORD: qw2fG2dfl0mxW
      DB_ENV_POSTGRES_DB: reviewdb
    networks:
      sync:
        ipv4_address: 172.16.238.11
    depends_on:
      - postgres-gerrit
  postgres-gerrit:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: qw2fG2dfl0mxW
      POSTGRES_DB: reviewdb
    networks:
      sync:
        ipv4_address: 172.16.238.10
networks:
  sync:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.238.0/24
